
################################################################################
# script for summarizing total RS and multiple mating by males and females
# Identifies genetic families and full sib relationships
# Makes plots of fertilization types based on sites size, brood, etc

# Heather Kenny-Duddela
# July 10, 2025
################################################################################

# libraries
library(tidyverse)

## load data

# All generated by script "paternity 2023 with lcmlkin output"

# table of assigned parents
assign23 <- read.csv("01_output-files/kin_2023_assigned_parents.csv")

# table of all adult-kid relatedness values
kin23.po <- read.csv("01_output-files/kin_2023_parent_offspring_all.csv")

# full kinship table (not just parent-offspring)
load("01_output-files/kin2_23.Rdata")


#-------------------------------------------------------------------------------
# Create wide format table with one row per offspring
#-------------------------------------------------------------------------------

# switch to wide format, each row is a kid, cols for dad and mom

# first just do dads
po.dad.wide <- subset(assign23, assign23$type_ind1=="dad")
# pull out only cols that need to get "dad" labels added
po.dad.wide2 <- po.dad.wide %>% select(Ind2,k0_hat:FamilyID_ind1)
# add "dad" labels
colnames(po.dad.wide2)[2:6] <- paste(colnames(po.dad.wide2)[2:6],"dad", sep="_")
colnames(po.dad.wide2)[7:11] <- gsub("ind1", "dad", colnames(po.dad.wide2)[7:11])


# do same for moms
po.mom.wide <- subset(assign23, assign23$type_ind1=="mom")
po.mom.wide2 <- po.mom.wide %>% select(Ind2,k0_hat:FamilyID_ind1)
# add "mom" labels
colnames(po.mom.wide2)[2:6] <- paste(colnames(po.mom.wide2)[2:6],"mom", sep="_")
colnames(po.mom.wide2)[7:11] <- gsub("ind1", "mom", colnames(po.mom.wide2)[7:11])

# pull out columns with relevant kid info, and no duplicated kids
po.kids <- assign23[-which(duplicated(assign23$Ind2)),c(2,15:23)]

# add dad columns to kid table
po.wide.d <- left_join(po.kids, po.dad.wide2, by="Ind2")

# add mom columns to kid table
po.wide <- left_join(po.wide.d, po.mom.wide2, by="Ind2")

# create column to specify genetic family, kids with same genetic mom and dad
po.wide$genetic_fam <- paste(po.wide$band_dad, po.wide$band_mom, sep="_")

# move genetic family label near the front of the table
po.wide2 <- po.wide[,c(1, 31, 2:30)]


#-------------------------------------------------------------------------------
# Add column for categorical site size
#-------------------------------------------------------------------------------

unique(po.wide2$site_ind2)

po.wide2$site_type <- NA

po.wide2$site_type[which(po.wide2$site_ind2 == "Plumbumpy" |
                           po.wide2$site_ind2 == "Speedwell" |
                           po.wide2$site_ind2 == "Cathys" |
                           po.wide2$site_ind2 == "Jays" |
                           po.wide2$site_ind2 == "Red Wagon" |
                           po.wide2$site_ind2 == "Karens")] <- "solitary"

po.wide2$site_type[which(po.wide2$site_ind2 == "Struthers" |
                           po.wide2$site_ind2 == "Urban Farm Girlz")] <- "small"

po.wide2$site_type[which(po.wide2$site_ind2 == "Boyer" |
                           po.wide2$site_ind2 == "Make Believe" |
                           po.wide2$site_ind2 == "Cooks" |
                           po.wide2$site_ind2 == "Blue Cloud")] <- "medium"

# reorder factors 
po.wide2$site_type <- factor(po.wide2$site_type,
                             levels=c("solitary","small","medium"))

#-------------------------------------------------------------------------------
# summary table of shared fert for each genetic family, with fert type
#-------------------------------------------------------------------------------

shared.fert <- po.wide2 %>%
  group_by(genetic_fam, band_dad, band_mom,
           site_dad, site_ind2, FamilyID_dad, FamilyID_mom, 
           FamilyID_ind2, site_type) %>%
  summarize(fert=n())

# add labels to specify fertilization type: within-pair (wp), extra-pair same site (ep_same), 
# extra-pair different site (ep_diff), ep_unsampled (sire is not known, but is not social dad) 

shared.fert$fert_type <- NA
shared.fert$fert_type[which(shared.fert$FamilyID_dad == 
                                   shared.fert$FamilyID_ind2)] <- "wp"
shared.fert$fert_type[which(is.na(shared.fert$FamilyID_dad))] <- "ep_unsampled"
shared.fert$fert_type[which(shared.fert$FamilyID_dad != shared.fert$FamilyID_ind2 &
                                   shared.fert$site_dad == shared.fert$site_ind2)] <- "ep_same"
shared.fert$fert_type[which(shared.fert$FamilyID_dad != shared.fert$FamilyID_ind2 &
                                   shared.fert$site_dad != shared.fert$site_ind2)] <- "ep_diff"

# for the non-wp ferts, double check that social dad was included in sequencing
non.wp <- subset(shared.fert, shared.fert$fert_type!="wp")
seq.dads <- subset(kin23.po, kin23.po$type_ind1=="dad")
assign.dads <- subset(assign23, assign23$type_ind1=="dad")

# note that corrected familyID for Boyer male at Boyer-05 is only in the
# assigned table
# All non.wp ferts had social dads included in sequencing
non.wp.check <- non.wp[-which(non.wp$FamilyID_ind2 %in% seq.dads$FamilyID_ind1 |
                                non.wp$FamilyID_ind2 %in% assign.dads$FamilyID_ind1), ]


#-------------------------------------------------------------------------------
# pull out full-sib relatedness values based on genetic families
# resolve uncertain paternity of CHR sire
# save shared.fert table
#-------------------------------------------------------------------------------

# get list of unique genetic families with mom and dad IDs known
known.gen.fam <- subset(po.wide, !is.na(po.wide$FamilyID_dad) & 
                          !is.na(po.wide$FamilyID_mom))
num.gen.fam <- unique(known.gen.fam$genetic_fam) # 48

# loop through the different families

# storage for full genetic sibs
sib.storage <- kin2.23[1,]
sib.storage[,] <- NA
sib.storage$genetic_fam <- NA

for (i in 1:length(num.gen.fam)) {
  # table of kids within the same genetic family
  fam <- subset(known.gen.fam, known.gen.fam$genetic_fam == num.gen.fam[i])
  # check how many kids there are
  if (length(unique(fam$Ind2)) > 1) 
    { # if more than one, pull them all out of the full kinship table
    gen.sib <- subset(kin2.23, kin2.23$Ind1 %in% fam$Ind2 &
                        kin2.23$Ind2 %in% fam$Ind2)
    # record genetic family ID
    gen.sib$genetic_fam <- num.gen.fam[i]
    # add these siblings to the storage table
    sib.storage <- rbind(sib.storage, gen.sib)
    }
}

# remove row of NAs
sib.storage <- subset(sib.storage, !is.na(sib.storage$Ind1))

# plot relatedness values for full sibs. 
plot(sib.storage$k0_hat, sib.storage$pi_HAT)
hist(sib.storage$pi_HAT)
range(sib.storage$pi_HAT) # pi_HAT range 0.253 - 0.660

# check for site-level differences in sib relatedness
ggplot(sib.storage, aes(x=pi_HAT)) + 
  geom_histogram(aes(fill=site_ind1), color="black") +
  facet_grid(site_ind1~.) +
  xlab("Estimated relatedness") +
  ggtitle("Full sibling relatedness across sites") +
  theme( strip.text.y = element_blank() )

ggsave("02_output-files/full sib kinship by site.png", h=8, w=6, scale=0.8)

# save full sib minimum relatedness
full.sib.pi.cutoff <- min(sib.storage$pi_HAT)

## Possible CHR sire has relatedness well within the full-sib range, so he 
# is a brother but not a sire. Remove him from the assigned table and shared.fert

# remove from assign23
kin23.assign.updated <- subset(assign23, assign23$site_ind1 != "CHR")

# remove from po.wide
po.wide3 <- subset(po.wide2, po.wide2$site_dad != "CHR"  |
                            is.na(po.wide2$site_dad)) # to not lose NA values

# remove from shared.fert
shared.fert2 <- subset(shared.fert, shared.fert$site_dad!= "CHR" |
                         is.na(shared.fert$site_dad))

# save updated tables
write.csv(kin23.assign.updated, 
          "02_output-files/kin_2023_assigned_parents_updated.csv",
          row.names=F)
write.csv(po.wide3, "02_output-files/kin_2023_po_wide.csv", row.names=F)
write.csv(shared.fert2, "02_output-files/fert_2023_by_genetic_fam.csv", 
          row.names = F)

#-------------------------------------------------------------------------------
# visualize shared.fert by genetic fam
#-------------------------------------------------------------------------------

# summarise number and proportion of each offspring type
total.fert <- sum(shared.fert2$fert)

fert.type.summary <- shared.fert2 %>%
  group_by(fert_type) %>%
  summarise(num.fert = sum(fert),
            prop.fert = num.fert/total.fert)


## By nest site ----------------------------------------------------------------

# summarize fertilization types within nest sites
fert.site.sum <- shared.fert2 %>%
  group_by(site_ind2, fert_type, site_type) %>%
  summarise(num.fert = sum(fert))

# reorder sites factors to be by increasing size
fert.site.sum$site_ind2 <- factor(fert.site.sum$site_ind2, 
                                  levels=c("Red Wagon","Plumbumpy","Karens",
                                           "Speedwell","Jays", "Cathys",
                                           "Urban Farm Girlz","Struthers",
                                           "Blue Cloud","Make Believe",
                                           "Cooks","Boyer"))

# reorder fert_type so the colors look better
fert.site.sum$fert_type <- factor(fert.site.sum$fert_type, 
                                  levels=c("ep_diff","ep_same",
                                           "ep_unsampled","wp"))

# get colors for plot
scales::viridis_pal()(length(unique(fert.site.sum$fert_type)))
# "#440154FF" "#31688EFF" "#35B779FF" "#FDE725FF"

ggplot(fert.site.sum, 
       aes(x=site_ind2, y=num.fert, fill=fert_type)) + 
  geom_bar(position="stack", stat="identity") +
  theme(axis.text.x = element_text(angle=90)) +
  scale_fill_manual(values=c("#FDE725FF","#31688EFF","#35B779FF","#440154FF")) + 
  ggtitle("Number of fertilization types by site") +
  xlab("Nest site") + ylab("Number of\n fertilizations")

ggsave("02_output-files/fert type number by site 2023.png", w=5, h=5)

## By site size ----------------------------------------------------------------

ggplot(fert.site.sum, 
       aes(x=site_type, y=num.fert, fill=fert_type)) + 
  geom_bar(position="fill", stat="identity") +
  theme(axis.text.x = element_text(angle=90)) +
  scale_fill_manual(values=c("#FDE725FF","#31688EFF","#35B779FF","#440154FF")) + 
  ggtitle("Proportion of fertilization types by site size") +
  xlab("Site size") + ylab("Proportion of\n fertilizations")

ggsave("02_output-files/fert type prop by size 2023.png", w=5, h=5)

## By female ID ----------------------------------------------------------------

# calculate total female RS
fem.tot.rs <- shared.fert2 %>%
  group_by(band_mom) %>%
  summarise(fem.tot.fert = sum(fert))

# calculate total wp fert per female
fem.tot.wp <- shared.fert2 %>% filter(fert_type=="wp") %>%
  group_by(band_mom) %>%
  summarise(fem.tot.wp = sum(fert))

# add to tot.rs table
fem.tot.rs2 <- left_join(fem.tot.rs, fem.tot.wp, by="band_mom")
fem.tot.rs2$fem.tot.wp[which(is.na(fem.tot.rs2$fem.tot.wp))] <- 0
# column for prop.ep
fem.tot.rs2$prop.ep <- (fem.tot.rs2$fem.tot.fert - fem.tot.rs2$fem.tot.wp)/
  fem.tot.rs2$fem.tot.fert
# remove NA row
fem.tot.rs3 <- fem.tot.rs2 %>% filter(!is.na(band_mom))


# add total RS to shared.fert2
shared.fert2.fem <- left_join(shared.fert2 %>% filter(!is.na(band_mom)), 
                              fem.tot.rs,
                              by="band_mom")
ggplot(shared.fert2.fem, 
       aes(x=reorder(band_mom, fem.tot.fert), y=fert, fill=fert_type)) + 
  geom_bar(position="stack", stat="identity") +
  theme(axis.text.x = element_text(angle=90)) +
  scale_fill_manual(values=c("#FDE725FF","#31688EFF","#35B779FF","#440154FF")) + 
  ggtitle("Total fertilizations per female by type") +
  xlab("Female band") + ylab("Number of\n fertilizations")

ggsave("02_output-files/female tot rs by fert type.png", h=4, w=6)



#-------------------------------------------------------------------------------
# summarize shared.fert by clutch and brood
#-------------------------------------------------------------------------------

shared.fert.clutch <- po.wide3 %>% 
  group_by(clutchID_ind2, band_dad, band_mom,
           site_dad, site_ind2, FamilyID_dad, FamilyID_mom, 
           FamilyID_ind2, site_type, brood_ind2) %>%
  summarize(fert=n())

# add labels to specify fertilization type: within-pair (wp), extra-pair same site (ep_same), 
# extra-pair different site (ep_diff), sire is unknown but is not social dad (ep_unsampled) 

shared.fert.clutch$fert_type <- NA
shared.fert.clutch$fert_type[which(shared.fert.clutch$FamilyID_dad == 
                              shared.fert.clutch$FamilyID_ind2)] <- "wp"
shared.fert.clutch$fert_type[which(
  is.na(shared.fert.clutch$FamilyID_dad))] <- "ep_unsampled"
shared.fert.clutch$fert_type[which(
  shared.fert.clutch$FamilyID_dad != shared.fert.clutch$FamilyID_ind2 &
                              shared.fert.clutch$site_dad == 
    shared.fert.clutch$site_ind2)] <- "ep_same"
shared.fert.clutch$fert_type[which(shared.fert.clutch$FamilyID_dad 
                                   != shared.fert.clutch$FamilyID_ind2 &
                              shared.fert.clutch$site_dad != 
                                shared.fert.clutch$site_ind2)] <- "ep_diff"


# proportion of within-pair offspring per clutch
shared.fert.clutch3 <- shared.fert.clutch %>% 
  group_by(clutchID_ind2) %>%
  mutate(clutch_size = sum(fert))

# table to calculate prop_wp
shared.fert.clutch.wp <- subset(shared.fert.clutch3, 
                                shared.fert.clutch3$fert_type=="wp")
shared.fert.clutch.wp <- shared.fert.clutch.wp %>%
  mutate(prop.wp = fert/clutch_size)

shared.fert.clutch.wp2 <- left_join(shared.fert.clutch3, 
                                    shared.fert.clutch.wp[,c(1,14)], 
                                    by="clutchID_ind2")
shared.fert.clutch.wp2$prop.wp[which(
  is.na(shared.fert.clutch.wp2$prop.wp))] <- 0

# table for plotting with one row per clutch
clutch.wp.plot <- subset(
  shared.fert.clutch.wp2 %>% 
    select(clutchID_ind2, band_mom, site_ind2, site_type,
           brood_ind2, clutch_size, prop.wp),
  duplicated(shared.fert.clutch.wp2 %>% 
               select(clutchID_ind2, band_mom, site_ind2, site_type,
                      brood_ind2, clutch_size, prop.wp)) == F)

ggplot(clutch.wp.plot, aes(x=prop.wp)) +
  geom_histogram(fill="#440154FF", color="black") +
  xlab("Proportion of within-pair offspring") + ylab("Count") + 
  ggtitle("Distirbution of within-pair proportions per clutch")

ggsave("02_output-files/prop within pair by clutch.png")

# Facet by brood and columns are by female -------------------------------------

# reorder fert_type factors
shared.fert.clutch.wp2$fert_type <- factor(shared.fert.clutch.wp2$fert_type, 
                                           levels=c("ep_diff","ep_same",
                                                    "ep_unsampled","wp"))

# reorder brood factors
shared.fert.clutch.wp2$brood_ind2 <- factor(shared.fert.clutch.wp2$brood_ind2,
                                            levels=c("collected","1","2"))

# note that 6-egg clutch for BlueCloud-06 is real
ggplot(subset(shared.fert.clutch.wp2, 
              !is.na(shared.fert.clutch.wp2$FamilyID_mom)),
              aes(x=FamilyID_mom, y=fert, fill=fert_type)) +
  geom_bar(position="stack", stat="identity") +
  theme(axis.text.x = element_text(angle=90)) +
  facet_grid(brood_ind2~.) +
  scale_fill_manual(values=c("#FDE725FF","#31688EFF","#35B779FF","#440154FF")) + 
  ggtitle("Fertilization types by brood and female") +
  xlab("Female familyID") + ylab("Number of\n fertilizations")

ggsave("02_output-files/fert types by brood and female 2023.png", w=7, h=4)

## for Dulog sites only
ggplot(subset(shared.fert.clutch.wp2, 
              !is.na(shared.fert.clutch.wp2$FamilyID_mom) &
                (shared.fert.clutch.wp2$site_ind2=="Boyer" |
                shared.fert.clutch.wp2$site_ind2=="Blue Cloud" |
                shared.fert.clutch.wp2$site_ind2=="Cooks" |
                shared.fert.clutch.wp2$site_ind2=="Make Believe")),
       aes(x=FamilyID_mom, y=fert, fill=fert_type)) +
  geom_bar(position="stack", stat="identity") +
  theme(axis.text.x = element_text(angle=90)) +
  facet_grid(brood_ind2~.) +
  scale_fill_manual(values=c("#FDE725FF","#31688EFF","#35B779FF","#440154FF")) + 
  ggtitle("Fertilization types by brood and female") +
  xlab("Female familyID") + ylab("Number of\n fertilizations")

ggsave("02_output-files/fert types by brood and female dulog sites 2023.png", 
       w=7, h=4)

## Dulog sites and only females with both collected and brood1

# females with each brood
fem.collected <- subset(shared.fert.clutch.wp2, 
                        shared.fert.clutch.wp2$brood_ind2=="collected")
fem.brood1 <- subset(shared.fert.clutch.wp2, 
                     shared.fert.clutch.wp2$brood_ind2=="1")
fem.brood2 <- subset(shared.fert.clutch.wp2, 
                     shared.fert.clutch.wp2$brood_ind2=="2")

# females with brood collected and 1
fem.col.1 <- subset(shared.fert.clutch.wp2, 
                    shared.fert.clutch.wp2$FamilyID_mom %in% 
                      fem.collected$FamilyID_mom &
                      shared.fert.clutch.wp2$FamilyID_mom %in% 
                      fem.brood1$FamilyID_mom)

ggplot(subset(fem.col.1, 
              !is.na(fem.col.1$FamilyID_mom) &
                fem.col.1$brood_ind2 != "2"),
       aes(x=FamilyID_mom, y=fert, fill=fert_type)) +
  geom_bar(position="stack", stat="identity") +
  theme(axis.text.x = element_text(angle=90)) +
  facet_grid(brood_ind2~.) +
  scale_fill_manual(values=c("#31688EFF","#35B779FF","#440154FF")) + 
  ggtitle("Fertilization types by brood and female") +
  xlab("Female familyID") + ylab("Number of\n fertilizations")

ggsave("02_output-files/fert types by collected and brood1 dulog sites.png", 
       w=5, h=4)

#-------------------------------------------------------------------------------
# Calculate total reproductive success for each male
#-------------------------------------------------------------------------------

# monitored males will have familyID represented in kid familyIDs
males.monitored <- subset(seq.dads, seq.dads$FamilyID_ind1 %in%
                            po.wide3$FamilyID_ind2)

# pull out monitored males from shared fert list
# add Boyer-05 and UrbanFarm-07 because social IDs are incorrect in the 
# seq.dads table. Cooks-02.2 because his social nest was monitored but was
# predated before it could be sampled. He does have EP ferts
fert.males.monitored <- subset(shared.fert2, shared.fert2$FamilyID_dad %in%
                                 males.monitored$FamilyID_ind1 |
                                 shared.fert2$FamilyID_dad == "Boyer-05" |
                                 shared.fert2$FamilyID_dad == "UrbanFarm-07" |
                                 shared.fert2$FamilyID_dad == "Cooks-02.2")

# check for males with zero RS that are in males.monitored but not fert
males.zeroRS <- subset(males.monitored, 
                       males.monitored$band_ind1 %in% 
                         fert.males.monitored$band_dad == F)

male.zeroRS.list <- unique(males.zeroRS %>% select(band_ind1, FamilyID_ind1))
male.zeroRS.list$site_dad <- c("Cooks", "Make Believe", "Make Believe","Urban Farm Girlz","Cooks")
male.zeroRS.list$male.tot.fert <- 0
colnames(male.zeroRS.list)[1] <- "band_dad"

# summarize across monitored males
fert.male.tot <- fert.males.monitored %>%
  group_by(band_dad, site_dad) %>%
  summarise(male.tot.fert=sum(fert))

# add zero RS males
fert.male.tot2 <- rbind(fert.male.tot, male.zeroRS.list[,c(1,3,4)])

# calculate total wp chicks
fert.male.wp <- fert.males.monitored %>% filter(fert_type=="wp") %>%
  group_by(band_dad) %>%
  summarise(male.tot.wp = sum(fert))

# add to total rs
fert.male.tot3 <- left_join(fert.male.tot2, fert.male.wp, by="band_dad")
fert.male.tot3$male.tot.wp[which(is.na(fert.male.tot3$male.tot.wp))] <- 0
# calculate proportion wp
fert.male.tot3$male.prop.ep <- (fert.male.tot3$male.tot.fert - 
  fert.male.tot3$male.tot.wp)/fert.male.tot3$male.tot.fert
# fix NaN
fert.male.tot3$male.prop.ep[which(fert.male.tot3$male.tot.fert==0)] <- 0


ggplot(fert.male.tot2, aes(x=reorder(band_dad, male.tot.fert), y=male.tot.fert,
                           fill=site_dad)) + 
  geom_bar(color="black", stat="identity") +
  theme(axis.text.x = element_text(angle=90)) +
  scale_fill_viridis_d() +
  ggtitle("Total reproductive success for each male") +
  xlab("Male band number") + ylab("Total offspring")

ggsave("02_output-files/tot RS per male color by site.png", w=6, h=4)

# add tot.chicks to shared.fert
shared.fert.clutch4 <- left_join(shared.fert.clutch3, 
                                 fert.male.tot2[,c(1,3)], by="band_dad")

# plot RS by fert type for males
ggplot(subset(shared.fert.clutch4, 
              !is.na(shared.fert.clutch4$band_dad)),
       aes(x=reorder(band_dad, male.tot.fert), y=fert, fill=fert_type)) + 
  geom_bar(position="stack", stat="identity") +
  theme(axis.text.x = element_text(angle=90)) +
  scale_fill_manual(values=c("#FDE725FF","#31688EFF","#440154FF")) + 
  ggtitle("Number of fertilization types by male") +
  xlab("Male band") + ylab("Number of\n fertilizations")

ggsave("02_output-files/male tot rs by fert type.png", h=4, w=6)

# facet by brood

# reorder brood levels
shared.fert.clutch4$brood_ind2 <- factor(shared.fert.clutch4$brood_ind2,
                                         levels=c("collected", "1", "2"))

ggplot(subset(shared.fert.clutch4, 
              !is.na(shared.fert.clutch4$band_dad)),
       aes(x=reorder(band_dad, male.tot.fert), y=fert, fill=fert_type)) + 
  geom_bar(position="stack", stat="identity") +
  theme(axis.text.x = element_text(angle=90)) +
  facet_grid(brood_ind2~.) +
  scale_fill_manual(values=c("#FDE725FF","#31688EFF","#440154FF")) + 
  ggtitle("Number of fertilization types by male and brood") +
  xlab("Male band") + ylab("Number of\n fertilizations")

ggsave("02_output-files/male tot rs by fert type and brood.png", h=4, w=6)

#-------------------------------------------------------------------------------
# Save key data tables
#-------------------------------------------------------------------------------

# fertilization types by clutch
write.csv(shared.fert.clutch3, "02_output-files/fert_2023_by_clutchID.csv",
          row.names=F)

# female total fertilizations
write.csv(fem.tot.rs3, "02_output-files/female total fert.csv", row.names = F)

# male total fertilizations
write.csv(fert.male.tot3, "02_output-files/male total fert.csv", row.names=F)











