
################################################################################
# Exploratory plots for CO 2022 fert net and nest distance data
# Heather Kenny-Duddela
# April 15, 2025
# updated May 28, 2026
################################################################################


#-------------------------------------------------------------------------------

## load libraries
library(tidyverse)


## Load data

# within-barn shared fertilizations with nest distances and overlap in focal
# female fertile period and focal male active nest. Generated by the script 
# make-full-data-table
net.raw <- read.csv("input-files/edge list distance and fert_with fertile and rest SI.csv")

# keep only birds at CHR
net.chr <- subset(net.raw, net.raw$barn=="CHR")

# remove unbanded males
unb <- grep("unb", net.chr$male)
net2 <- net.chr[-unb, ]

## load bird attributes (plumage color)
attr.raw <- read.csv("input-files/AdultData2022_fromDatabase.csv")

# keep only CHR birds
attr <- subset(attr.raw, attr.raw$site=="Colorado Horse Rescue")

## add TS column for each sex
fem <- subset(attr, attr$sex=="F"|attr$sex=="F?")
male <- subset(attr, attr$sex=="M"|attr$sex=="M")

# make column for TS, using RTS unless it is missing, in which case use LTS
fem$TS <- fem$mean_rts
fem$TS[which(is.na(fem$TS))] <- fem$mean_lts[which(is.na(fem$TS))]

male$TS <- male$mean_rts
male$TS[which(is.na(male$TS))] <- male$mean_lts[which(is.na(male$TS))]

## Add scaled variables
fem.scaled <- as.data.frame(lapply(select(fem, TS, throat_avg_bright, 
                                          breast_avg_bright, belly_avg_bright,
                                          vent_avg_bright), scale))
colnames.fem.scaled <- paste(colnames(fem.scaled),"scaled",sep="_")
colnames(fem.scaled) <- colnames.fem.scaled
fem.join <- cbind(fem, fem.scaled)

male.scaled <- as.data.frame(lapply(select(male, TS, throat_avg_bright, 
                                          breast_avg_bright, belly_avg_bright,
                                          vent_avg_bright), scale))
colnames.male.scaled <- paste(colnames(male.scaled),"scaled",sep="_")
colnames(male.scaled) <- colnames.male.scaled
male.join <- cbind(male, male.scaled)

attr2 <- rbind(fem.join, male.join)

write.csv(attr2, "output-files/pheno-CHR-for-unscaling.csv", row.names = F)


# summarize to figure out discrepancy with other summary stats

fem.pheno <- fem.join %>% select(TS, TS_scaled,
                                 throat_avg_bright, throat_avg_bright_scaled,
                                 breast_avg_bright, breast_avg_bright_scaled)

# make summary stat table (empty)
summary.stats.fem.all <- as.data.frame(matrix(NA, nrow=5, ncol=6))
colnames(summary.stats.fem.all) <- colnames(fem.pheno)
# sample size
summary.stats.fem.all[1,] <- colSums(!is.na(fem.pheno))
# mean
summary.stats.fem.all[2,] <- apply(fem.pheno, 2 ,mean,na.rm=T)
# sd
summary.stats.fem.all[3,] <- apply(fem.pheno, 2, sd, na.rm=T)
# min
summary.stats.fem.all[4,] <- apply(fem.pheno, 2, min, na.rm=T)
# max
summary.stats.fem.all[5,] <- apply(fem.pheno, 2, max, na.rm=T)
# transpose
t.summary.stats.fem.all <- as.data.frame(t(as.matrix(summary.stats.fem.all)))
# add column labels
colnames(t.summary.stats.fem.all) <- c("N","mean","sd","min","max")



#-------------------------------------------------------------------------------
# Format tables for using igraph
#-------------------------------------------------------------------------------

## igraph likes to receive data about edges and nodes (vertices) separately

# keep only edge data from net, and only existing edges (no zeros)
net.el <- select(net2, female, male, shared_fert, attempt1, soc.pair, total.dur, 
                 process.dist.m, barn) %>%
  filter(shared_fert>0)

# make node attributes table
# first specify sex
sex <- pivot_longer(net2[,c(1:2,5)], cols=c("female","male"),  names_to="sex", 
                    values_to="band")
sex2 <- unique.data.frame(sex)

# add morph and plumage color
attr.pheno <- select(attr2, band, mass_1, throat_avg_bright:vent_total_bright, 
                     mean_rwl, mean_rts, mean_lts, TS:vent_avg_bright_scaled )
net.node <- left_join(sex2, attr.pheno, by="band")
# put band column first
net.node2 <- cbind(net.node[,3], net.node[,c(1,2,4:29)])


################################################################################
## plumage color and ferts

# add plumage to net2

# harmonize column names
colnames(net2)[1] <- "band"

# perform merge for females
net3 <- left_join(net2, attr.pheno, by="band")
colnames(net3)[20:45] <- paste("fem", colnames(net3)[20:45], sep="_")

# perform merge for males
colnames(net3)[1:2] <- c("female","band")
net4 <- left_join(net3, attr.pheno, by="band")
colnames(net4)[46:71] <- paste("male", colnames(net4)[46:71], sep="_")
colnames(net4)[2] <- "male"


# save new table with plumage
write.csv(net4, "output-files/fert dist plumage-CHRonly_with fertile and rest SI.csv", 
          row.names = F)


